name: 'Json Composite Action'
description: 'Execute Json Operations In A Composite Action'
inputs:
  secrets:
    description: 'Secrets'
    required: true
  actionInputs:
    description: 'Inputs'
    required: true
  enable-extended-ops:
    type: boolean
    description: Enable Extended Ops
outputs:
  json-action-outputs:
    description: "Json Composite Action Outputs"
    value: ${{ toJSON(steps.json-ops.outputs) }}
  json-action-extended-outputs:
    description: "Json Composite Action Outputs"
    value: ${{ toJSON(steps.json-extended-ops.outputs) }}    
  has-extended-outputs:
    description: "Json Composite Action Outputs"
    value: false
runs:
  using: "composite"
  steps:
    - name: Json Operations
      id: json-ops
      run: |
         echo "Extended Ops Enabled? ${{ inputs.enable-extended-ops || false }}"
         echo "Extended Ops Enabled? ${{ inputs.enable-extended-ops }}"
         echo "Json Action Working Directory: ${GITHUB_WORKSPACE}"
         echo "Json Ops First Number ${FIRST_NUMBER}"
         echo "Json Ops Second Number: ${SECOND_NUMBER}"
         echo "result=some stuff" >> $GITHUB_OUTPUT
      shell: bash
      env:
        SECRET1: ${{ fromJSON(inputs.secrets).SECRET1 }}
        FIRST_NUMBER: ${{ fromJSON(inputs.actionInputs).add-action-first-value }}
        SECOND_NUMBER: ${{ fromJSON(inputs.actionInputs).add-action-second-value }}
    - name: Json Extended Operations
      # if: ${{ inputs.enable-extended-ops || false }} == 'true'
      if: inputs.enable-extended-ops == 'true'
      id: json-extended-ops
      run: |
         echo inputs.enable-extended-ops: ${{ inputs.enable-extended-ops }}
         echo "Json Extended Ops First Number ${FIRST_NUMBER}"
         echo "Json Extended Ops Second Number: ${SECOND_NUMBER}"
         echo "extended-ops-info=things and such" >> $GITHUB_OUTPUT
         echo "extended-ops-data=Maybe a larger payload, maybe in json" >> $GITHUB_OUTPUT
         echo "extended-ops-results-path=Path to some folder" >> $GITHUB_OUTPUT
      shell: bash
      env:
        SECRET1: ${{ fromJSON(inputs.secrets).SECRET1 }}
        FIRST_NUMBER: ${{ fromJSON(inputs.actionInputs).add-action-first-value }}
        SECOND_NUMBER: ${{ fromJSON(inputs.actionInputs).add-action-second-value }}        

#    - name: Random Number Generator
#      id: random-number-generator
#      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
#      shell: bash
#
#    - name: Set GitHub Path
#      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
#      shell: bash
#      env:
#        GITHUB_ACTION_PATH: ${{ github.action_path }}
#
#    - name: Run goodbye.sh
#      run: goodbye.sh
#      shell: bash


