name: 'Json Composite Action'
description: 'Execute Json Operations In A Composite Action'
inputs:
  secrets:
    description: 'Secrets'
    required: true
  actionInputs:
    description: 'Inputs'
    required: true
outputs:
  json-action-outputs:
    description: "Json Composite Action Outputs"
    value: ${{ steps.json-ops.outputs.result }}
runs:
  using: "composite"
  steps:
    - name: Json Operations
      id: json-ops
      run: |
         echo "Json Ops First Number ${FIRST_NUMBER}"
         echo "Json Ops Second Number: ${SECOND_NUMBER}"
         echo "result=json stuff" >> $GITHUB_OUTPUT
      shell: bash
      env:
        SECRET1: ${{ fromJSON(inputs.secrets).SECRET1 }}
        FIRST_NUMBER: ${{ fromJSON(inputs.actionInputs).first }}
        SECOND_NUMBER: ${{ fromJSON(inputs.actionInputs).second }}

#    - name: Random Number Generator
#      id: random-number-generator
#      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
#      shell: bash
#
#    - name: Set GitHub Path
#      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
#      shell: bash
#      env:
#        GITHUB_ACTION_PATH: ${{ github.action_path }}
#
#    - name: Run goodbye.sh
#      run: goodbye.sh
#      shell: bash


